# ログイン
# @name login
POST {{host}}/auth/login
content-type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

@token = {{login.response.body.$.token}}

###

# ユーザ一覧取得
GET {{host}}/userList
content-type: application/json
Authorization:  Bearer {{token}}

###

# ユーザ追加
POST {{host}}/userList
content-type: application/json
Authorization:  Bearer {{token}}

{
  "order": 1,
  "name": "{{$guid}}",
  "status": "退社",
  "destination": "",
  "return": "",
  "update_at": "",
  "message": "",
  "version": "",
  "email": ""
}

###

# ユーザ削除
DELETE {{host}}/userList/5
content-type: application/json
Authorization:  Bearer {{token}}

###

# ユーザ情報更新
PATCH  {{host}}/userList/4
content-type: application/json
Authorization:  Bearer {{token}}

{
  "name": "asdasd",
  "status": "asdasd"
}

###

# healthCheck更新
PATCH  {{host}}/healthCheck/4
content-type: application/json
Authorization:  Bearer {{token}}

{
  "healthCheckAt": ""
}

###

# appVersion更新
PATCH  {{host}}/updateAppVersion/4
content-type: application/json
Authorization:  Bearer {{token}}

{
  "mainAppVersion": "",
  "rendererAppVersion": ""
}

###

# changeOrder更新
PATCH  {{host}}/changeOrder/4
content-type: application/json
Authorization:  Bearer {{token}}

{
  "order": 99
}

###

# お知らせ情報取得
GET  {{host}}/appInfo
content-type: application/json
Authorization:  Bearer {{token}}

###

# お知らせ情報更新
PATCH   {{host}}/appInfo
content-type: application/json
Authorization:  Bearer {{token}}

{
  "main": {
    "latestVersion": "3.1.0",
    "updatedContents": ""
  },
  "renderer": {
    "latestVersion": "3.1.0a",
    "updatedContents": ""
  },
  "operatingTimeOfCompanyInfo": {
    "start": "08:00",
    "end": "22:00"
  }
}

###

# トイレ情報取得
GET {{host}}/restrooms
content-type: application/json
Authorization:  Bearer {{token}}

###

# トイレ情報更新
PATCH {{host}}/restrooms/2
content-type: application/json
Authorization:  Bearer {{token}}

{
  "isUsing": false
}

###

# 執務室情報取得
GET {{host}}/officeInfo
content-type: application/json
Authorization:  Bearer {{token}}

###

# 執務室情報更新
PATCH {{host}}/officeInfo
content-type: application/json
Authorization:  Bearer {{token}}

{
  "tempreture": 25.3,
  "humidity": 42.7
}

###

# 現在日時取得
GET {{host}}/getCurrentTime
content-type: application/json
Authorization:  Bearer {{token}}
