# ログイン
# @name login
POST {{host}}/auth/login
content-type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

@token = {{login.response.body.$.token}}

###

# ユーザ一覧取得
GET {{host}}/userList
content-type: application/json
Authorization:  Bearer {{token}}

###

# ユーザ追加
POST {{host}}/userList
content-type: application/json
Authorization:  Bearer {{token}}

{
  "order": 1,
  "name": "{{$guid}}",
  "status": "退社",
  "destination": "",
  "return": "",
  "update_at": "",
  "message": "",
  "version": "",
  "email": ""
}

###

# ユーザ削除
DELETE {{host}}/userList/4
content-type: application/json
Authorization:  Bearer {{token}}

###

# ユーザ情報更新
PATCH  {{host}}/userList/4
content-type: application/json
Authorization:  Bearer {{token}}

{
  "name": "あああ",
  "status": "FLEX"
}

###

# お知らせ情報取得
GET  {{host}}/notification
content-type: application/json
Authorization:  Bearer {{token}}

###

# お知らせ情報更新
PATCH   {{host}}/notification
content-type: application/json
Authorization:  Bearer {{token}}

{
  "content": "",
  "latestAppVersion": "3.1.0"
}

###

# トイレ情報取得
GET {{host}}/restrooms
content-type: application/json
Authorization:  Bearer {{token}}

###

# トイレ情報更新
PATCH {{host}}/restrooms/2
content-type: application/json
Authorization:  Bearer {{token}}

{
  "isUsing": false
}
